version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./wait-for-it.sh ${DATABASE_HOST}:${DATABASE_PORT} -- ./main
    depends_on:
      - eccomerce-postgres
    working_dir: /root/
    restart: always
    env_file:
      - ".env"
    ports:
      - "${EXPOSE_PORT}:${EXPOSE_PORT}"


  eccomerce-postgres:
    image: postgres:15.3-alpine
    hostname: ${DATABASE_HOST}
    container_name: eccomerce-postgres
    command: -p ${DATABASE_PORT} # Change the default port
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # - PGPORT=${DATABASE_PORT}
    expose:
      - "${DATABASE_PORT}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart: always
    volumes:
      - eccomerce-postgres:/var/lib/postgresql/data

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - backend

  eccomerce-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: eccomerce-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

  # eccomerce-message-broker:
  #   image: rabbitmq:3-management-alpine
  #   container_name: message-broker
  #   ports:
  #     - 5672:5672 # for sender and consumer connections
  #     - 15672:15672 # for serve RabbitMQ GUI
  #   volumes:
  #     - rabbitmq-lib:/var/lib/rabbitmq
  #     - rabbitmq-log:/var/log/rabbitmq
  #   restart: always

volumes:
  eccomerce-postgres:
  # rabbitmq-lib:
  # rabbitmq-log: