version: '3.8'

services:
  web:
    container_name: go_web
    build: .
    env_file:
      - .env
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    # command: ./wait-for-it.sh postgres && go /usr/src/app/main.go -b 0.0.0.0
    depends_on:
      - postgres
    networks:
      - fullstack
  postgres:
    image: postgres:13.11
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  api:
  postgres-db:

networks:
  fullstack:
    driver: bridge