version: '3.8'

services:
  # postgres:
  #     image: postgres:13.11
  #     environment:
  #       - POSTGRES_USER=${POSTGRES_USER}
  #       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #       - POSTGRES_DB=${POSTGRES_DB}
  #     restart: always
  #     # ports:
  #     #   - "5432:5432"
  #     volumes:
  #       - ./db_files:/var/lib/postgresql/data
  #     networks:
  #       - fullstack
  web:
    container_name: go_web
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - ./:/usr/src/app/
    # command: ./wait-for-it.sh postgres:5432 -- ./main
    command: ./main
    # depends_on:
    #   - postgres
    # networks:
    #   - fullstack

# networks:
#   fullstack:
#     driver: bridge